version: '3.2'
services:
  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./reverse.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8080"
    networks:
      - some-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  some-net:
    driver: bridge
